# Generated by Django 5.0.6 on 2026-03-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barberos", "0001_initial"),
        ("clientes", "0001_initial"),
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField()),
                (
                    "duracion_minutos",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutos"),
                            (30, "30 minutos"),
                            (60, "60 minutos"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmado", "Confirmado"),
                            ("atendido", "Atendido"),
                            ("cancelado", "Cancelado"),
                            ("no_show", "No Show"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "precio_cobrado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "barbero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="barberos.barbero",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas",
                        to="servicios.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "ordering": ["-fecha_hora"],
            },
        ),
    ]
