# Generated by Django 5.0.6 on 2026-03-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="duracion_minutos",
            field=models.IntegerField(
                choices=[
                    (15, "15 minutos"),
                    (30, "30 minutos"),
                    (45, "45 minutos"),
                    (60, "60 minutos"),
                    (90, "90 minutos"),
                    (120, "120 minutos"),
                ],
                default=30,
            ),
        ),
    ]
