# Generated by Django 5.0.6 on 2026-03-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("interno", "Interno"),
                        ],
                        default="interno",
                        max_length=10,
                    ),
                ),
                ("destinatario", models.CharField(max_length=100)),
                ("mensaje", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviado", "Enviado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("enviado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="citas.cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-creado_en"],
            },
        ),
    ]
