# Generated by Django 5.0.6 on 2026-03-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("telefono", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "preferencias",
                    models.TextField(
                        blank=True, help_text="Ej: siempre degradado, barba corta"
                    ),
                ),
                (
                    "notas_internas",
                    models.TextField(
                        blank=True, help_text="Solo visible para el staff"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
    ]
