# Generated by Django 5.0.6 on 2026-03-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categorías de Producto",
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_compra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stock_actual", models.IntegerField(default=0)),
                (
                    "stock_minimo",
                    models.IntegerField(
                        default=5, help_text="Alerta cuando el stock baje de este valor"
                    ),
                ),
                ("unidad", models.CharField(default="unidad", max_length=20)),
                ("activo", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.categoriaproducto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("stock_anterior", models.IntegerField()),
                ("stock_nuevo", models.IntegerField()),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Venta #123 o Compra #45",
                        max_length=100,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Stock",
                "verbose_name_plural": "Movimientos de Stock",
                "ordering": ["-fecha"],
            },
        ),
    ]
