# Generated by Django 5.0.6 on 2026-03-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías de Servicio",
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "duracion_minutos",
                    models.PositiveIntegerField(
                        default=30, help_text="Duración en minutos"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="servicios/"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicios",
                        to="servicios.categoriaservicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["nombre"],
            },
        ),
    ]
