# Generated by Django 5.0.6 on 2026-03-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servicios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barbero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comision_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="% de comisión por servicio",
                        max_digits=5,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("especialidad", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "servicios",
                    models.ManyToManyField(
                        blank=True, related_name="barberos", to="servicios.servicio"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_barbero",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Barbero",
                "verbose_name_plural": "Barberos",
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_entrada", models.TimeField(blank=True, null=True)),
                ("hora_salida", models.TimeField(blank=True, null=True)),
                ("notas", models.CharField(blank=True, max_length=200)),
                (
                    "barbero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="barberos.barbero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "ordering": ["-fecha"],
                "unique_together": {("barbero", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="HorarioLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "barbero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="barberos.barbero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario Laboral",
                "verbose_name_plural": "Horarios Laborales",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("barbero", "dia_semana")},
            },
        ),
    ]
